Homepage:
    pattern:  /
    defaults: { _controller: "Application:Index:index"}

Create_Module:
    pattern:  /module/create
    defaults: { _controller: "Application:Index:createmodule"}

Lookup_Packagist:
    pattern:  /module/packagist/lookup
    defaults: { _controller: "Application:Index:lookupPackagist"}

Module_Screenshot_Upload:
    pattern:  /module/screenshot/upload
    defaults: { _controller: "Application:Index:uploadScreenshot"}

Save_Module:
    pattern:  /module/save
    defaults: { _controller: "Application:Index:savemodule"}
