imports:
    - { resource: ../base/app.yml }

modules:
    module_listener_options:
        config_cache_enabled: true
        module_map_cache_enabled: true

monolog:
    handlers:
        main:
            type:  stream
            path:  %app.logs_dir%/%app.environment%.log
            level: warning